spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d0me0jogjchc738f0cgg-a.frankfurt-postgres.render.com:5432/mealkitservice
    username: mealkitservice_user
    password: zQHMYnRtqCqbNMgfPGjPNKrDqHMw1pnx
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
