spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-patient-smoke-a9coto8g-pooler.gwc.azure.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_Wzx6LXQUgt9f
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 60000
#      password: "" # Optional, if your Redis server has authentication
      lettuce:
        pool:
          max-active: 10 # Adjust as per your need
          max-wait: 10000 # Max wait time before throwing exception
          max-idle: 5 # Max idle connections
          min-idle: 1 # Min idle connections

jwt:
  secret: zrke4wpL1OQYMy32A95eY7FgKoTBYdke7zRrAVOpC3U=
  expiration: 86400000 # 1 روز (به میلی‌ثانیه)


